//<span class="link-costellazione" onclick="openMiniModal('orsa-maggiore', event)">grande carro</span>
//`<span class="scaled-text"> </span>`
const costellazioni = {
  "orsa-maggiore": {
    nome: "Orsa Maggiore",
    immagine: "img/orsa_maggiore.jpg",
    mitologia: `<span class="scaled-text">Nella mitologia classica una delle ninfe compagne di Artemide, Callisto, ebbe un figlio con Zeus, Arcade. Era, arrabbiata, trasformò Callisto in un'orsa. Arcade quasi uccise la madre mentre stava cacciando, ma Zeus e Artemide lo fermarono e posero entrambi in cielo come l'Orsa Maggiore e Arturo (guardiano dell'orsa), la stella più brillante della costellazione di <span class="link-costellazione" onclick="openMiniModal('boote', event)">Boote</span>. Secondo un'altra leggenda, Arcade è stato trasformato da Era in un cucciolo d'orso e posto nel cielo al fianco della madre. Era, tuttavia, non era contenta del fatto che fossero stati assunti in cielo e perciò chiese aiuto a Teti: questa, una dea marina, rivolse alle costellazioni una maledizione perché fossero costrette a girare per sempre in tondo nel cielo e a non riposarsi mai sotto l'orizzonte, spiegando così il fatto che queste costellazioni sono circumpolari.</span>`,
    stelle: ["Alioth, la stella principale", "Dubhe", "Alkaid", "Mizar, una stella doppia (Alcor), visibili anche ad occhio nudo", "Merak", "Phecda", "Megrez"],
    visibilita: `<span class="scaled-text">Tutto l’anno, in particolare tra marzo e maggio</span>`,
    mesiVisibili: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    trova: `<span class="scaled-text">E' tra le costellazioni più visibili e facilmente localizzabili!</span>`,
    informazioni: `<span class="scaled-text">E' una delle costellazioni più facilmente individuabili e visibile del cielo notturno. Solitamente ci si riferisce all'asterismo come Grande Carro, cioè le sette stelle più luminose, ma ci sono altre stelle a comporre l'intera costellazione dell'Orsa Maggiore. La seconda stella del manico del Carro, Mizar è una stella doppia, visibile addirittura ad occhio nudo! La più luminosa è la terza stella del carro, Alioth.</span>`,
  },
  "cassiopea": {
    nome: "Cassiopea",
    immagine: "img/cassiopea.jpg",
    mitologia: `<span class="scaled-text">Nella mitologia greca la regina Cassiopea, moglie vanitosa del re <span class="link-costellazione" onclick="openMiniModal('cefeo', event)">Cefeo</span>, un giorno si proclamò più bella delle Nereidi (le ninfe marine). Queste, infuriate dai commenti di Cassiopea, chiesero al dio del mare Poseidone di punire Cassiopea. Poseidone inviò il mostro Caetus (la balena) per devastare il regno di Cefeo. Il re, su consiglio di un oracolo, decise di sacrificare al mostro la figlia <span class="link-costellazione" onclick="openMiniModal('andromeda', event)">Andromeda</span>. <span class="link-costellazione" onclick="openMiniModal('perseo', event)">Perseo</span> salvò Andromeda e la sposò, ma la subdola Cassiopea tramò con l'ex amante della figlia di uccidere Perseo. Il marito di Andromeda usò la testa di Medusa per tramutare in pietra l'ex amante, Cassiopea e i loro soldati. Poseidone alla fine posizionò Cassiopea e Cefeo vicini nel cielo come punizione.</span>`,
    stelle: ["Schedar, la stella più luminosa", "Caph", "Chi", "Navi", "Ruchbah"],
    informazioni: `<span class="scaled-text"> Cassiopea è una delle costellazioni più facili da trovare nel cielo notturno, caratterizzata da una forma a "W".al di sopra della terza stella ci sono i resti di una supernova esplosa circa 11000 anni fa.</span >`,
    visibilita: `<span class= "scaled-text" > Tutto l'anno, in particolare tra settembre e marzo</span>`,
    mesiVisibili: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
          trova: `<span class="scaled-text">Una volta individuato il <span class="link-costellazione" onclick="openMiniModal('orsa-maggiore', event)">grande carro</span> e il <span class="link-costellazione" onclick="openMiniModal('orsa-minore', event)">piccolo carro</span> Cassiopea si trova esattamente dall'altra parte del grande carro rispetto al piccolo.</span>`,
  },
  "orsa-minore": {
    nome: "Orsa Minore",
    immagine: "img/orsa_minore.jpg",
      informazioni: `<span class="scaled-text">La costellazione del piccolo carro è sempre stata tra le più importanti in antichità, infatti la sua stella più luminosa, la Stella Polare, indica quasi perfettamente il nord, in quanto l'asse di rotazione terrestre è inclinato proprio verso la sua direzione.</span>`,
      mitologia: `<span class="scaled-text">Secondo alcune leggende l'orsa minore raffigurerebbe Arcade, cioè il figlio illeggittimo di Zeus e Callisto (una ninfa, compagna di Artemide). Arcade, durante una battuta di caccia, stava per uccidere sua madre trasformata in un'orsa. Zeus ed Era intervenirono e trasformarono pure Arcade in un cucciolo d'orso e lo posero nel cielo a fianco della <span class="link-costellazione" onclick="openMiniModal('orsa-maggiore', event)">madre</span>.</span>`,
    stelle: ["Stella Polare, attorno alla quale ruota l'intera volta celeste", "Kochab", "Pherckad"],
      visibilita: `<span class="scaled-text">Tutto l’anno</span>`,
    mesiVisibili: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      trova: `<span class="scaled-text">Individua le ultime due stelle che compongono il <span class="link-costellazione" onclick="openMiniModal('orsa-maggiore', event)">grande carro</span>, a questo punto prosegui verso l'alto fino a trovare una stella abbastanza luminosa, quella è la Stella Polare.</span>`,
  },
  "boote": {
    nome: "Boote",
    immagine: "img/boote.jpg",
      mitologia: `<span class="scaled-text">Le storie dietro l'origine di questa costellazione sono molteplici. Spesso la costellazione, ed in particolare la stella Artura, vengono definite come "il guardiano dell'orso", in riferimento alle due costellazioni confindanti dell'<span class="link-costellazione" onclick="openMiniModal('orsa-maggiore', event)">Orsa maggiore</span> e l'<span class="link-costellazione" onclick="openMiniModal('orsa-minore', event)">Orsa minore</span>.  In altri miti Boote è l'inventore dell'aratro e quindi viene posto a fianco del grande carro, stando ad indicare il passaggio dalla vita nomade a quella sedentaria.</span>`,
    stelle: ["Arturo, la stella più luminosa", "Izar", "Seginus", "Nekkar", "Muphrid"],
      informazioni: `<span class="scaled-text">Detto anche il pastore, o bovaro. La sua stella più luminosa, Arturo, è quarta più brillante del cielo boreale.</span>`,
      visibilita: `<span class="scaled-text">Da marzo ad agosto</span>`,
    mesiVisibili: [3, 4, 5, 6, 7, 8],
      trova: `<span class="scaled-text">Una volta individuato il <span class="link-costellazione" onclick="openMiniModal('orsa-maggiore', event)">grande carro</span>, procedendo dal carro e seguendo l'arco del manico si può notare una stella molto luminosa, Arturo. Boote si estenderà da questa stella luminosa in direzione del manico del carro.</span>`,
  },
  "orione": {
    nome: "Orione",
    immagine: "img/orione.jpg",
      mitologia: `<span class="scaled-text">La prima raffigurazione di Orione risale a circa 30000 anni fa, in un'incisione su un pezzo d'avorio. Nella mitologia sumera Orione era associato a Gilgamesh, che combatteva nel cielo contro il <span class="link-costellazione" onclick="openMiniModal('toro', event)">toro</span>. Nella mitologia greca era il figlio di Poseidone e amava andare a caccia. Un giorno, Orione si vantò di poter cacciare qualsiasi essere vivente sulla faccia della terra, quindi Gaia, la dea della terra, inviò uno <span class="link-costellazione" onclick="openMiniModal('scorpione', event)">scorpione</span> per metterlo alla prova. Lo scorpione punse il cacciatore, ma che riuscì ad ucciderlo prima di morire. Zeus decise di porre Orione e lo scorpione ai lati opposti della volta celeste, cosicché non potessero mai più vedersi e smettessero per sempre di combattere.</span>`,
    stelle: ["Betelgeuse, la stella più luminosa", "Rigel", "Bellatrix", "Alnitak", "Alnilam", "Mintaka", "Saiph", "Meissa", "Nebulosa di Orione, che è una regione di formazione stellare, la più vicina alla Terra", "Nebulosa testa di cavallo"],
      informazioni: `<span class="scaled-text">È una delle costellazioni più famose e caratteristiche del nostro cielo. Si distingue chiaramente per le tre stelle molto vicine che compongono la sua "cintura". Betelgeuse è la stella più luminosa e brilla di un colore rosso. Rigel è la seconda stella più luminosa e al di sotto della cintura si può vedere con un semplice binocolo, la famosissima nebulosa di Orione.</span>`,
      visibilita: `<span class="scaled-text">Da novembre a aprile</span>`,
    mesiVisibili: [11, 12, 1, 2, 3, 4],
      trova: `<span class= "scaled-text" > Orione è una delle costellazioni più facilmente visibili del nostro cielo invernale. Subito dopo il tramonto, guardando verso sud-est, si potrà vedere la costellazione sorgere, mentre a notte inoltrata lo si potrà individuare in direzione ovest, prossimo a tramontare.</span>`,
  },
  "toro": {
    nome: "Toro",
    immagine: "img/toro.jpg",
      mitologia: `<span class="scaled-text">Una delle 12 costellazioni dello zodiaco</span>`,
    stelle: ["Work in progress"],
      oggetti: `<span class="scaled-text">Work in progress</span>`,
      visibilita: `<span class="scaled-text">Da novembre a marzo</span>`,
    mesiVisibili: [11, 12, 1, 2, 3],
      trova: `<span class="scaled-text">Work in progress</span>`,
  },
  "cigno": {
    nome: "Cigno",
    immagine: "img/cigno.jpg",
      mitologia: `<span class="scaled-text">Work in progress</span>`,
    stelle: ["Work in progress"],
      oggetti: `< span class= "scaled-text" > Work in progress</span>`,
      visibilita: `<span class="scaled-text">Da giugno ad ottobre</span>`,
      mesiVisibili: [6, 7, 8, 9, 10],
      trova: `<span class="scaled-text">Work in progress</span>`,
  },
  "aquila": {
    nome: "Aquila",
    immagine: "img/aquila.jpg",
    mitologia: "Work in progress",
    stelle: ["Work in progress"],
    oggetti: "Work in progress",
    visibilita: "Da giugno ad ottobre",
      mesiVisibili: [6, 7, 8, 9, 10],
      trova: `<span class="scaled-text">Work in progress</span>`,
  },
  "lira": {
    nome: "Lira",
    immagine: "img/lira.jpg",
    mitologia: "Work in progress",
    stelle: ["Work in progress"],
    oggetti: "Work in progress",
    visibilita: "Da maggio ad ottobre",
      mesiVisibili: [5, 6, 7, 8, 9, 10],
      trova: `<span class="scaled-text">Work in progress</span>`,
  },
  "gemelli": {
    nome: "Gemelli",
    immagine: "img/gemelli.jpg",
    mitologia: "Work in progress",
    stelle: ["Work in progress"],
    oggetti: "Work in progress",
    visibilita: "Da dicembre ad aprile",
    mesiVisibili: [12, 1, 2, 3, 4],
  },
  "ariete": {
    nome: "Ariete",
    immagine: "img/ariete.jpg",
    mitologia: "Work in progress",
    stelle: ["Work in progress"],
    oggetti: "Work in progress",
    visibilita: "Da ottobre a febbraio",
      mesiVisibili: [10, 11, 12, 1, 2],
      trova: `<span class="scaled-text">Work in progress</span>`,
  },
  "cancro": {
    nome: "Cancro",
    immagine: "img/cancro.jpg",
    mitologia: "Work in progress",
    stelle: ["Work in progress"],
    oggetti: "Work in progress",
    visibilita: "Da gennaio a maggio",
      mesiVisibili: [1, 2, 3, 4, 5],
      trova: `<span class="scaled-text">Work in progress</span>`,
  },
  "leone": {
    nome: "Leone",
    immagine: "img/leone.jpg",
    mitologia: "Work in progress",
    stelle: ["Work in progress"],
    oggetti: "Work in progress",
    visibilita: "Da febbraio a giugno",
      mesiVisibili: [2, 3, 4, 5, 6],
      trova: `<span class="scaled-text">Work in progress</span>`,
  },
  "vergine": {
    nome: "Vergine",
    immagine: "img/vergine.jpg",
    mitologia: "Work in progress",
    stelle: ["Work in progress"],
    oggetti: "Work in progress",
    visibilita: "Da marzo a luglio",
      mesiVisibili: [3, 4, 5, 6, 7],
      trova: `<span class="scaled-text">Work in progress</span>`,
  },
  "bilancia": {
    nome: "Bilancia",
    immagine: "img/bilancia.jpg",
    mitologia: "Work in progress",
    stelle: ["Work in progress"],
    oggetti: "Work in progress",
    visibilita: "Da maggio a settembre",
      mesiVisibili: [5, 6, 7, 8, 9],
      trova: `<span class="scaled-text">Work in progress</span>`,
  },
  "scorpione": {
    nome: "Scorpione",
    immagine: "img/scorpione.jpg",
    mitologia: "Work in progress",
    stelle: ["Work in progress"],
    oggetti: "Work in progress",
    visibilita: "Da giugno ad agosto",
      mesiVisibili: [6, 7, 8],
      trova: `<span class="scaled-text">Work in progress</span>`,
  },
  "ofiuco": {
    nome: "Ofiuco",
    immagine: "img/ofiuco.jpg",
    mitologia: "Work in progress",
    stelle: ["Work in progress"],
    oggetti: "Work in progress",
    visibilita: "Da giugno ad ottobre",
      mesiVisibili: [6, 7, 8, 9, 10],
      trova: `<span class="scaled-text">Work in progress</span>`,
  },
  "sagittario": {
    nome: "Sagittario",
    immagine: "img/sagittario.jpg",
    mitologia: "Work in progress",
    stelle: ["Work in progress"],
    oggetti: "Work in progress",
    visibilita: "Da giugno ad ottobre",
      mesiVisibili: [6, 7, 8, 9, 10],
      trova: `<span class="scaled-text">Work in progress</span>`,
  },
  "capricorno": {
    nome: "Capricorno",
    immagine: "img/capricorno.jpg",
    mitologia: "Work in progress",
    stelle: ["Work in progress"],
    oggetti: "Work in progress",
    visibilita: "Da agosto a novembre",
      mesiVisibili: [8, 9, 10, 11],
      trova: `<span class="scaled-text">Work in progress</span>`,
  },
  "acquario": {
    nome: "Acquario",
    immagine: "img/acquario.jpg",
    mitologia: "Work in progress",
    stelle: ["Work in progress"],
    oggetti: "Work in progress",
    visibilita: "Da agosto a dicembre",
      mesiVisibili: [8, 9, 10, 11, 12],
      trova: `<span class="scaled-text">Work in progress</span>`,
  },
  "pesci": {
    nome: "Pesci",
    immagine: "img/pesci.jpg",
    mitologia: "Work in progress",
    stelle: ["Work in progress"],
    oggetti: "Work in progress",
    visibilita: "Da settembre a gennaio",
      mesiVisibili: [9, 10, 11, 12, 1],
      trova: `<span class="scaled-text">Work in progress</span>`,
  },
  "cane-minore": {
    nome: "Cane Minore",
    immagine: "img/cane_minore.jpg",
    mitologia: "Work in progress",
    stelle: ["Procione"],
    oggetti: "Work in progress",
    visibilita: "Da dicembre a maggio",
      mesiVisibili: [12, 1, 2, 3, 4, 5],
      trova: `<span class="scaled-text">Work in progress</span>`,
  },
  "cane-maggiore": {
    nome: "Cane Maggiore",
    immagine: "img/cane_maggiore.jpg",
    mitologia: "Una delle 12 costellazioni dello zodiaco",
    stelle: ["Betelgeuse", "Rigel", "Bellatrix"],
    oggetti: "Work in progress",
    visibilita: "Da dicembre a marzo",
      mesiVisibili: [12, 1, 2, 3],
      trova: `<span class="scaled-text">Work in progress</span>`,
  },
  "auriga": {
    nome: "Auriga",
    immagine: "img/auriga.jpg",
    mitologia: "Una delle 12 costellazioni dello zodiaco",
    stelle: ["Betelgeuse", "Rigel", "Bellatrix"],
    oggetti: "Work in progress",
    visibilita: "Da novembre a marzo",
      mesiVisibili: [11, 12, 1, 2, 3],
      trova: `<span class="scaled-text">Work in progress</span>`,
  },

};
