const costellazioni = {
  "orsa-maggiore": {
    nome: "Orsa Maggiore",
    immagine: "img/orsa_maggiore.jpg",
    mitologia: "Nella mitologia classica una delle ninfe compagne di Artemide, Callisto, perse la sua verginità con Zeus, che si era avvicinato sotto le spoglie della stessa Artemide; arrabbiata, Era la trasformò in un orso. Il figlio di Callisto, Arcas, quasi uccise la madre mentre stava cacciando, ma Zeus e Artemide lo fermarono e posero entrambi in cielo come l'Orsa Maggiore e l'Orsa Minore. Era, tuttavia, non era contenta del fatto che fossero stati assunti in cielo e perciò chiese aiuto a Teti: questa, una dea marina, rivolse alle costellazioni una maledizione perché fossero costrette a girare per sempre in tondo nel cielo e a non riposarsi mai sotto l'orizzonte, spiegando così il fatto che queste costellazioni sono circumpolari.",
    stelle: ["Alioth, la stella principale", "Dubhe", "Alkaid", "Mizar", "Merak", "Phecda", "Megrez", "Include M81, M82 e altre galassie."],
    visibilita: "Tutto l’anno, in particolare tra marzo e maggio",
    mesiVisibili: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    trova: "E' tra le costellazioni più visibili e facilmente localizzabili!",
    informazioni: "E' una delle costellazioni più facilmente individuabili e visibile del cielo notturno. Solitamente ci si riferisce all'asterismo come Grande Carro, cioè le sette stelle più luminose, ma ci sono altre stelle a comporre l'intera costellazione dell'Orsa Maggiore. La seconda stella del manico del Carro, Mizar è una stella doppia, visibile addirittura ad occhio nudo! La più luminosa è la terza stella del carro, Alioth.",
  },
  "cassiopea": {
    nome: "Cassiopea",
    immagine: "img/cassiopea.jpg",
    mitologia: "Cassiopea era una regina vanitosa...",
    stelle: ["Schedar", "Caph", "Ruchbah"],
    oggetti: "Contiene la Nebulosa Cuore e Anima.",
    visibilita: "Tutto l'anno, in particolare tra settembre e marzo",
    mesiVisibili: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  },
  "orsa-minore": {
    nome: "Orsa Minore",
    immagine: "img/orsa_minore.jpg",
    mitologia: "La cucciola di orsa",
    stelle: ["Stella Polare", "Tutta la volta celeste ruota attorno alla Stella Polare"],
    visibilita: "Tutto l’anno",
    mesiVisibili: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    trova: "Individua le ultime due stelle che compongono il carro, a questo punto prosegui verso l'alto fino a trovare una stella abbastanza luminosa, quella è la Stella Polare.",
  },
  "boote": {
    nome: "Boote",
    immagine: "img/boote.jpg",
    mitologia: "Il bovaro, colui che ara i campi",
    stelle: ["Arturo"],
    oggetti: "Presenta una delle stelle più luminose del cielo boreale",
    visibilita: "Da marzo ad agosto",
    mesiVisibili: [3, 4, 5, 6, 7, 8],
  },
  "orione": {
    nome: "Orione",
    immagine: "img/orione.jpg",
    mitologia: "Un cacciatore munito di spada ed arco",
    stelle: ["Betelgeuse", "Rigel", "Bellatrix"],
    oggetti: "La famosissima nebulosa di Orione, ma pure le tre stelle vicine che compongono la cintura di Orione",
    visibilita: "Da novembre a aprile",
    mesiVisibili: [11, 12, 1, 2, 3, 4],
  },
  "toro": {
    nome: "Toro",
    immagine: "img/toro.jpg",
    mitologia: "Una delle 12 costellazioni dello zodiaco",
    stelle: ["Betelgeuse", "Rigel", "Bellatrix"],
    oggetti: "La famosissima nebulosa di Orione, ma pure le tre stelle vicine che compongono la cintura di Orione",
    visibilita: "Da novembre a marzo",
    mesiVisibili: [11, 12, 1, 2, 3],
  },
  "cigno": {
    nome: "Cigno",
    immagine: "img/cigno.jpg",
    mitologia: "Il bovaro, colui che ara i campi",
    stelle: ["Arturo"],
    oggetti: "Presenta una delle stelle più luminose del cielo boreale",
    visibilita: "Da giugno ad ottobre",
    mesiVisibili: [6, 7, 8, 9, 10],
  },
  "aquila": {
    nome: "Aquila",
    immagine: "img/aquila.jpg",
    mitologia: "Il bovaro, colui che ara i campi",
    stelle: ["Arturo"],
    oggetti: "Presenta una delle stelle più luminose del cielo boreale",
    visibilita: "Da giugno ad ottobre",
    mesiVisibili: [6, 7, 8, 9, 10],
  },
  "lira": {
    nome: "Lira",
    immagine: "img/lira.jpg",
    mitologia: "Il bovaro, colui che ara i campi",
    stelle: ["Arturo"],
    oggetti: "Presenta una delle stelle più luminose del cielo boreale",
    visibilita: "Da maggio ad ottobre",
    mesiVisibili: [5, 6, 7, 8, 9, 10],
  },
  "gemelli": {
    nome: "Gemelli",
    immagine: "img/gemelli.jpg",
    mitologia: "Il bovaro, colui che ara i campi",
    stelle: ["Arturo"],
    oggetti: "Presenta una delle stelle più luminose del cielo boreale",
    visibilita: "Da dicembre ad aprile",
    mesiVisibili: [12, 1, 2, 3, 4],
  },
  "ariete": {
    nome: "Ariete",
    immagine: "img/ariete.jpg",
    mitologia: "Il bovaro, colui che ara i campi",
    stelle: ["Arturo"],
    oggetti: "Presenta una delle stelle più luminose del cielo boreale",
    visibilita: "Da ottobre a febbraio",
    mesiVisibili: [10, 11, 12, 1, 2],
  },
  "cancro": {
    nome: "Cancro",
    immagine: "img/cancro.jpg",
    mitologia: "Il bovaro, colui che ara i campi",
    stelle: ["Arturo"],
    oggetti: "Presenta una delle stelle più luminose del cielo boreale",
    visibilita: "Da gennaio a maggio",
    mesiVisibili: [1, 2, 3, 4, 5],
  },
  "leone": {
    nome: "Leone",
    immagine: "img/leone.jpg",
    mitologia: "Il bovaro, colui che ara i campi",
    stelle: ["Arturo"],
    oggetti: "Presenta una delle stelle più luminose del cielo boreale",
    visibilita: "Da febbraio a giugno",
    mesiVisibili: [2, 3, 4, 5, 6],
  },
  "vergine": {
    nome: "Vergine",
    immagine: "img/vergine.jpg",
    mitologia: "Il bovaro, colui che ara i campi",
    stelle: ["Arturo"],
    oggetti: "Presenta una delle stelle più luminose del cielo boreale",
    visibilita: "Da marzo a luglio",
    mesiVisibili: [3, 4, 5, 6, 7],
  },
  "bilancia": {
    nome: "Bilancia",
    immagine: "img/bilancia.jpg",
    mitologia: "Il bovaro, colui che ara i campi",
    stelle: ["Arturo"],
    oggetti: "Presenta una delle stelle più luminose del cielo boreale",
    visibilita: "Da maggio a settembre",
    mesiVisibili: [5, 6, 7, 8, 9],
  },
  "scorpione": {
    nome: "Scorpione",
    immagine: "img/scorpione.jpg",
    mitologia: "Il bovaro, colui che ara i campi",
    stelle: ["Arturo"],
    oggetti: "Presenta una delle stelle più luminose del cielo boreale",
    visibilita: "Da giugno ad agosto",
    mesiVisibili: [6, 7, 8],
  },
  "ofiuco": {
    nome: "Ofiuco",
    immagine: "img/ofiuco.jpg",
    mitologia: "Il bovaro, colui che ara i campi",
    stelle: ["Arturo"],
    oggetti: "Presenta una delle stelle più luminose del cielo boreale",
    visibilita: "Da giugno ad ottobre",
    mesiVisibili: [6, 7, 8, 9, 10],
  },
  "sagittario": {
    nome: "Sagittario",
    immagine: "img/sagittario.jpg",
    mitologia: "Il bovaro, colui che ara i campi",
    stelle: ["Arturo"],
    oggetti: "Presenta una delle stelle più luminose del cielo boreale",
    visibilita: "Da giugno ad ottobre",
    mesiVisibili: [6, 7, 8, 9, 10],
  },
  "capricorno": {
    nome: "Capricorno",
    immagine: "img/capricorno.jpg",
    mitologia: "Il bovaro, colui che ara i campi",
    stelle: ["Arturo"],
    oggetti: "Presenta una delle stelle più luminose del cielo boreale",
    visibilita: "Da agosto a novembre",
    mesiVisibili: [8, 9, 10, 11],
  },
  "acquario": {
    nome: "Acquario",
    immagine: "img/acquario.jpg",
    mitologia: "Il bovaro, colui che ara i campi",
    stelle: ["Arturo"],
    oggetti: "Presenta una delle stelle più luminose del cielo boreale",
    visibilita: "Da agosto a dicembre",
    mesiVisibili: [8, 9, 10, 11, 12],
  },
  "pesci": {
    nome: "Pesci",
    immagine: "img/pesci.jpg",
    mitologia: "Il bovaro, colui che ara i campi",
    stelle: ["Arturo"],
    oggetti: "Presenta una delle stelle più luminose del cielo boreale",
    visibilita: "Da settembre a gennaio",
    mesiVisibili: [9, 10, 11, 12, 1],
  },
  "cani-da-caccia": {
    nome: "Cani da Caccia",
    immagine: "img/cani_da_caccia.jpg",
    mitologia: "Una coppia di cani appartenenti a Boote che mordono la zampa dell'orsa maggiore",
    stelle: ["Arturo"],
    oggetti: "Presenta una delle stelle più luminose del cielo boreale",
    visibilita: "Da marzo a luglio",
    mesiVisibili: [3, 4, 5, 6, 7],
  },
  "cane-maggiore": {
    nome: "Cane Maggiore",
    immagine: "img/cane_maggiore.jpg",
    mitologia: "Una delle 12 costellazioni dello zodiaco",
    stelle: ["Betelgeuse", "Rigel", "Bellatrix"],
    oggetti: "La famosissima nebulosa di Orione, ma pure le tre stelle vicine che compongono la cintura di Orione",
    visibilita: "Da dicembre a marzo",
    mesiVisibili: [12, 1, 2, 3],
  },
  "auriga": {
    nome: "Auriga",
    immagine: "img/auriga.jpg",
    mitologia: "Una delle 12 costellazioni dello zodiaco",
    stelle: ["Betelgeuse", "Rigel", "Bellatrix"],
    oggetti: "La famosissima nebulosa di Orione, ma pure le tre stelle vicine che compongono la cintura di Orione",
    visibilita: "Da novembre a marzo",
    mesiVisibili: [11, 12, 1, 2, 3],
  },
};
