const costellazioni = {
  "orsa-maggiore": {
    nome: "Orsa Maggiore",
    immagine: "img/orsa_maggiore.png",
    mitologia: "Callisto trasformata in orsa da Zeus...",
    stelle: ["Dubhe", "Merak", "Alioth"],
    oggetti: "Include M81, M82 e altre galassie.",
    visibilita: "Tutto l’anno",
    mesiVisibili: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    informazioni: "E' una delle costellazioni più facilmente individuabili e visibile del cielo notturno, durante tutto l'anno.",
  },
  "cassiopea": {
    nome: "Cassiopea",
    immagine: "img/cassiopea.jpg",
    mitologia: "Cassiopea era una regina vanitosa...",
    stelle: ["Schedar", "Caph", "Ruchbah"],
    oggetti: "Contiene la Nebulosa Cuore e Anima.",
    visibilita: "Tutto l'anno",
    mesiVisibili: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  },
  // Aggiungi tutte le altre
  "orsa-minore": {
    nome: "Orsa Minore",
    immagine: "img/orsa_minore.jpg",
    mitologia: "La cucciola di orsa",
    stelle: ["Stella Polare"],
    oggetti: "Tutta la volta celeste ruota attorno alla Stella Polare",
    visibilita: "Tutto l’anno",
    mesiVisibili: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  },
  "boote": {
    nome: "Boote",
    immagine: "img/boote.jpg",
    mitologia: "Il bovaro, colui che ara i campi",
    stelle: ["Arturo"],
    oggetti: "Presenta una delle stelle più luminose del cielo boreale",
    visibilita: "Da gennaio ad ottobre",
    mesiVisibili: [1, 2, 3, 4, 5, 6, 7, 8, 9],
  },
  "orione": {
    nome: "Orione",
    immagine: "img/orione.jpg",
    mitologia: "Un cacciatore munito di spada ed arco",
    stelle: ["Betelgeuse", "Rigel", "Bellatrix"],
    oggetti: "La famosissima nebulosa di Orione, ma pure le tre stelle vicine che compongono la cintura di Orione",
    visibilita: "Da settembre a marzo",
    mesiVisibili: [9, 10, 11, 12, 1, 2, 3],
  },
};
